er_diff = G-R;
er_mul = G./R;

f = figure; figure(f)
set(f,'Position',[100,100,1000,300])
subplot(1,3,3)
ksdensity(er(:))
title('Log multiplicative error')
xlabel('err = 10log(G/R)')
ylabel('pdf')
axis([-50,50,0,0.06])
subplot(1,3,2)
ksdensity(er_mul(:))
title('Multiplicative error')
xlabel('err = G/R')
ylabel('pdf')
axis([-2,100,0,0.25])
subplot(1,3,1)
ksdensity(er_diff(:))
title('Additional error')
xlabel('err = G-R')
ylabel('pdf')
axis([-50,50,0,1.2])
saveas(f,'pdfs','png')